export const SYSTEM_ALARM_ROWS = [
  {
    id: 'system-1',
    deviceName: '空气源热泵1',
    alarmNameKey: 'high-pressure-protection',
    alarmName: '高压保护报警',
    level: '3',
    levelText: '三级',
    happenedAt: '2026-03-10 17:22:59',
    heatingSeason: '2026-03-10',
    suggestion: '检查冷凝器是否堵塞，并确认冷凝风机运行正常。',
  },
  {
    id: 'system-2',
    deviceName: '空气源热泵2',
    alarmNameKey: 'low-pressure-protection',
    alarmName: '低压保护报警',
    level: '3',
    levelText: '三级',
    happenedAt: '2026-03-10 16:48:12',
    heatingSeason: '2026-03-10',
    suggestion: '检查系统是否存在制冷剂泄漏，并确认蒸发器结霜情况。',
  },
  {
    id: 'system-3',
    deviceName: '空气源热泵3',
    alarmNameKey: 'compressor-overload',
    alarmName: '压缩机过载保护报警',
    level: '2',
    levelText: '二级',
    happenedAt: '2026-03-10 15:32:41',
    heatingSeason: '2026-03-09',
    suggestion: '检查压缩机电流、电压和回油情况。',
  },
  {
    id: 'system-4',
    deviceName: '空气源热泵4',
    alarmNameKey: 'outlet-sensor',
    alarmName: '出水温度传感器故障',
    level: '4',
    levelText: '四级',
    happenedAt: '2026-03-10 14:20:33',
    heatingSeason: '2026-03-08',
    suggestion: '检查传感器接线、信号及标定状态。',
  },
  {
    id: 'system-5',
    deviceName: '热泵循环泵',
    alarmNameKey: 'insufficient-flow',
    alarmName: '流量不足报警',
    level: '3',
    levelText: '三级',
    happenedAt: '2026-03-10 13:12:25',
    heatingSeason: '2026-03-06',
    suggestion: '检查过滤器、阀门开度和管路是否存在气堵。',
  },
]

export const HISTORY_ALARM_ROWS = [
  {
    id: 'history-1',
    deviceName: '空气源热泵5',
    alarmNameKey: 'high-pressure-protection',
    alarmName: '高压保护报警',
    level: '2',
    levelText: '二级',
    happenedAt: '2026-03-08 09:41:12',
    heatingSeason: '2026-03-08',
    processedAt: '2026-03-08 10:05:02',
    suggestion: '已清洗冷凝器并复位。',
  },
  {
    id: 'history-2',
    deviceName: '空气源热泵6',
    alarmNameKey: 'outlet-sensor',
    alarmName: '出水温度传感器故障',
    level: '4',
    levelText: '四级',
    happenedAt: '2026-03-06 18:12:40',
    heatingSeason: '2026-03-06',
    processedAt: '2026-03-06 18:40:11',
    suggestion: '已更换传感器并校准。',
  },
]
